name: Build
on:
  workflow_dispatch:

env:
  ORG_ENV: ${{ vars.ORG_ENV }}
  REPO_ENV: ${{ vars.REPO_ENV }}
  FLOW_ENV: "flow-env"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ ! -z "${{ secrets.ORG_SECRET }}" ]; then
          echo "Has ORG_SECRET"
          else
          echo "No ORG_SECRET"
          fi
          if [ ! -z "${{ secrets.REPO_SECRET }}" ]; then
          echo "Has REPO_SECRET"
          else
          echo "No REPO_SECRET"
          fi
          echo "${{ vars.ORG_ENV }} ${{ env.ORG_ENV }} $ORG_ENV"
          echo "${{ vars.REPO_ENV }} ${{ env.REPO_ENV }} $REPO_ENV"
          echo "${{ env.FLOW_ENV }} $FLOW_ENV"
